server:
  port: 8080

openremote:
  api-base-url: https://localhost            # OpenRemote Manager (/api)  -> HTTP
  keycloak-base-url: https://localhost/auth # Keycloak (/realms/.. )    -> HTTPS
  admin-realm: master
  client-id: iotservice
  client-secret: pbnXKSbELRZddPGbbnzVGJFovWzBESGQ

http:
  insecure-trust: true

logging:
  level:
    feign: DEBUG
    org.springframework.cloud.openfeign: DEBUG
