server:
  port: 8080

openremote:
  api-base-url: https://localhost
  keycloak-base-url: https://localhost/auth
  admin-realm: kasiskafe
  master-client-id: iotservice
  master-client-secret: pbnXKSbELRZddPGbbnzVGJFovWzBESGQ
  tenant-client-id: kasiskafe
  tenant-client-secret: VuJ8x8eLN7odFmXg1xxj2HQ9wcE0pYjo

http:
  insecure-trust: true

logging:
  level:
    root: INFO
    feign: DEBUG
    feign.Logger: DEBUG
    com.example.iot.service.client.openremote: DEBUG
    com.example.iot.service.configuration.feign: DEBUG

